logging:
  level:
    root: info
  path: E:/java/logs/student-manage-system

spring:
  application:
    name: student-manage-system
  datasource:
    url: jdbc:mysql://119.91.198.164:3306/ssm?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true